[package]
name = "plot_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.42"
vector3 = "1.1.4"
serialport = "4.3.0"
rand = "0.8.5"
